### ISSUE TITLE
react-hot-loader v1.3.1

### ISSUE THREAD

**Issue by cuongngosa** [mozilla-neutrino/react-starter#8]
```
WARNING in ./~/react-hot-loader/~/source-map/lib/source-map/source-node.js
8:45-52 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
```
Browser console error
Cannot find module "."       webpackMissingModule — source-map-generator.js

Pls let me know what I config wrong

**Comment by eliperelman** [comment]
I'm not sure how you ended up with react-hot-loader v1.3.1 since this repository has it set to a different version. The correct version should be: 3.0.0-beta.6. Please reinstall that dependency and try it again. Thanks!
