### ISSUE TITLE
HMR doesn't work

### ISSUE THREAD

**Issue by cuongngosa** [mozilla-neutrino/react-starter#9]
Hi, I tried run as copied.
I modified some text in App.js but doesn't see browser auto reload.

**Comment by eliperelman** [comment]
Could you provide some more details about versions and possible errors in your console? I see that in your other issue you were using the incorrect version of react-hot-loader, which should be set to 3.0.0-beta.6. Please post some more relevant information. Thanks!

**Comment by cuongngosa** [comment]
With this issue I tried as 3.0.0-beta.6 ( by repo clone).
I can't see any error in console, the problem I can't see text update affect on browser after change in App.js.

**Comment by cuongngosa** [comment]
Second time file save then it works
